-- One-time migration: add unique constraint on domain and seed 66 new clients
-- Run against production Vercel Postgres

-- Ensure domain uniqueness for ON CONFLICT to work
CREATE UNIQUE INDEX IF NOT EXISTS idx_clients_domain ON clients(domain);

INSERT INTO clients (name, domain, color, description, tier, seo_value, active)
VALUES
  ('Trinity Health', 'trinity-health.org', '#3B82F6', '', 'medium', 50, true),
  ('Comerica Park', 'comericapark.com', '#3B82F6', '', 'medium', 50, true),
  ('Comerica Bank', 'comerica.com', '#3B82F6', '', 'medium', 50, true),
  ('Costco', 'costco.com', '#3B82F6', '', 'medium', 50, true),
  ('Toyota', 'toyota.com', '#3B82F6', '', 'medium', 50, true),
  ('Eastern Michigan University', 'emich.edu', '#3B82F6', '', 'medium', 50, true),
  ('Shake Shack', 'shakeshack.com', '#3B82F6', '', 'medium', 50, true),
  ('Apple', 'apple.com', '#3B82F6', '', 'medium', 50, true),
  ('Cartier', 'cartier.com', '#3B82F6', '', 'medium', 50, true),
  ('COSM', 'cosm.com', '#3B82F6', '', 'medium', 50, true),
  ('PVS Chemicals', 'pvschemicals.com', '#3B82F6', '', 'medium', 50, true),
  ('Primark', 'primark.com', '#3B82F6', '', 'medium', 50, true),
  ('Celanese', 'celanese.com', '#3B82F6', '', 'medium', 50, true),
  ('Monroe Environmental', 'mon-env.com', '#3B82F6', '', 'medium', 50, true),
  ('Monroe Plumbing & Heating', 'monroeplumbing.com', '#3B82F6', '', 'medium', 50, true),
  ('John E. Green Company', 'johnegreencompany.com', '#3B82F6', '', 'medium', 50, true),
  ('Goyette Mechanical', 'goyettemechanical.com', '#3B82F6', '', 'medium', 50, true),
  ('DeeCramer', 'deecramer.com', '#3B82F6', '', 'medium', 50, true),
  ('W.J. O''Neil Company', 'wjoneil.com', '#3B82F6', '', 'medium', 50, true),
  ('John Darr Mechanical', 'booneanddarr.com', '#3B82F6', '', 'medium', 50, true),
  ('Motor City Electric', 'mcelectric.com', '#3B82F6', '', 'medium', 50, true),
  ('Veterans Affairs', 'va.gov', '#3B82F6', '', 'medium', 50, true),
  ('LivWell', 'livwell.com', '#3B82F6', '', 'medium', 50, true),
  ('Condat', 'condat.com', '#3B82F6', '', 'medium', 50, true),
  ('BASF', 'basf.com', '#3B82F6', '', 'medium', 50, true),
  ('Ameresco', 'ameresco.com', '#3B82F6', '', 'medium', 50, true),
  ('Genesee Polymers', 'geneseepolymers.com', '#3B82F6', '', 'medium', 50, true),
  ('YMCA', 'ymca.org', '#3B82F6', '', 'medium', 50, true),
  ('DiBella''s', 'dibellas.com', '#3B82F6', '', 'medium', 50, true),
  ('DEA', 'dea.gov', '#3B82F6', '', 'medium', 50, true),
  ('Flagstar Bank', 'flagstar.com', '#3B82F6', '', 'medium', 50, true),
  ('Roland Berger', 'rolandberger.com', '#3B82F6', '', 'medium', 50, true),
  ('TAG Heuer', 'tagheuer.com', '#3B82F6', '', 'medium', 50, true),
  ('Crown Enterprises', 'crownenterprises.com', '#3B82F6', '', 'medium', 50, true),
  ('Superior National Bank', 'snbt.com', '#3B82F6', '', 'medium', 50, true),
  ('Delta Air Lines', 'delta.com', '#3B82F6', '', 'medium', 50, true),
  ('Domino''s', 'dominos.com', '#3B82F6', '', 'medium', 50, true),
  ('Our Next Energy', 'one.ai', '#3B82F6', '', 'medium', 50, true),
  ('Fidelity', 'fidelity.com', '#3B82F6', '', 'medium', 50, true),
  ('MAHLE', 'mahle.com', '#3B82F6', '', 'medium', 50, true),
  ('University of Detroit Mercy', 'udmercy.edu', '#3B82F6', '', 'medium', 50, true),
  ('Starbucks', 'starbucks.com', '#3B82F6', '', 'medium', 50, true),
  ('MAXAR', 'maxar.com', '#3B82F6', '', 'medium', 50, true),
  ('Arhaus', 'arhaus.com', '#3B82F6', '', 'medium', 50, true),
  ('Louis Dreyfus', 'ldc.com', '#3B82F6', '', 'medium', 50, true),
  ('Smoothie King', 'smoothieking.com', '#3B82F6', '', 'medium', 50, true),
  ('Detroit Medical Center', 'dmc.org', '#3B82F6', '', 'medium', 50, true),
  ('Serra Ford', 'serraford.com', '#3B82F6', '', 'medium', 50, true),
  ('Lithia Motors', 'lithia.com', '#3B82F6', '', 'medium', 50, true),
  ('Verizon', 'verizon.com', '#3B82F6', '', 'medium', 50, true),
  ('Operating Engineers Local 324', 'iuoe324.org', '#3B82F6', '', 'medium', 50, true),
  ('Five Below', 'fivebelow.com', '#3B82F6', '', 'medium', 50, true),
  ('Hampton Manor', 'hamptonmanor.net', '#3B82F6', '', 'medium', 50, true),
  ('UWM', 'uwm.com', '#3B82F6', '', 'medium', 50, true),
  ('NSF International', 'nsf.org', '#3B82F6', '', 'medium', 50, true),
  ('Nissan', 'nissan.com', '#3B82F6', '', 'medium', 50, true),
  ('Comcast', 'comcast.com', '#3B82F6', '', 'medium', 50, true),
  ('Floor & Decor', 'flooranddecor.com', '#3B82F6', '', 'medium', 50, true),
  ('Bedford Michigan Schools', 'bedfordpublicschools.com', '#3B82F6', '', 'medium', 50, true),
  ('Buff City Soap', 'buffcitysoap.com', '#3B82F6', '', 'medium', 50, true),
  ('Suburban Cadillac', 'suburbancadillac.com', '#3B82F6', '', 'medium', 50, true),
  ('Quicken Loans', 'quickenloans.com', '#3B82F6', '', 'medium', 50, true),
  ('Fox Ann Arbor', 'foxannarbor.com', '#3B82F6', '', 'medium', 50, true),
  ('Amazon', 'amazon.com', '#3B82F6', '', 'medium', 50, true),
  ('Sugar Factory', 'sugarfactory.com', '#3B82F6', '', 'medium', 50, true),
  ('Ford Field', 'fordfield.com', '#3B82F6', '', 'medium', 50, true)
ON CONFLICT (domain) DO NOTHING;
